name: js Lint
#use ESLint

on:
  push:
    branches: [main, dev*]
  pull_request:
    branches: [main, dev*]
    
jobs:
  build:
  
   runs-on: ubuntu-latest
  
   steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      
      - run: npm ci
      #npm install과 같은 기능
      - run: npm run build --if-present
      - run: npm test
      - run: npm run lint
